### PR TITLE
Added option for number input

### PR DESCRIPTION
**Pull request by idanstark42**
image

The new number objective. In the scoresheet it has a `max` and `min` properties, replacing the old `enum` on numbers.

### CODE REVIEW

**Comment by scherrsj** [comment]
I like the look of the number objective control.

I did a test by changing M9 objective 2 from enum to number min=0, max=6 in the .js file
What I am seeing is a positive score value for the mission only when the objective-number value is **outside** the range of 0-6

Also, if I put in an unallowable value (e.g. -1 or 7) in the text field, then the value doesn't get replaced in the text field by the results of limitValueToRange.  I think that limitValueToRange is only being called onInit and not on ng-click.

What is the behavior if the user clicks + or - without having an initial value?  It appears that it uses "0" as the initial value.  There might be times when we want the initial value to be treated as min if the user clicks on + and max if the user clicks on -.  For example, consider M14 & Precision Tokens.  A single click on "-" could make the value 5, rather than 5 clicks on "+".  Would this work?

**Comment by idanstark42** [comment]
That's an excellent idea and a great catch on the bug! I didn't notice that. I'll fix it and add the -/+ min/max idea

**Comment by idanstark42** [comment]
Hi. I cannot seem to be able to reproduce it. Can you post your challenge.js?

**Comment by scherrsj** [comment]
[2019_US.js.zip](https://github.com/FirstLegoLeague/scoring/files/3562028/2019_US.js.zip)

I rebuilt in Win10 with node 10.13.0.  The total scoresheet score becomes 0 when I enter a value in M09 number field.  M09 is flagged as not having a valid score.  min/max limits work fine.

**Comment by scherrsj** [comment]
I found it.  It's in the challenge.js scoring function.  I was using === to compare string 2 and number 2, and it failed because the types don't match.  Using == instead works correctly.

**Comment by 2roy999** [comment]
We should not use `==` even in the `challenge.js`, we can convert the string to a number by using `new Number(str)`. We should be sure of that when generating the `challenge.js`

**Comment by scherrsj** [comment]
What if we use numeric values in the XML?  Will they come through as numbers in the .js?

**Comment by idanstark42** [comment]
I think not, but we should test and see. Can someone compose an XML with number objectives and build it into a JS for testing?

**Comment by alanggreen** [comment]
Steve, can you do that?

**Comment by scherrsj** [comment]
Yes, I will test it today.

Steve

**Comment by scherrsj** [comment]
I have a patch for scoresheet-builder that will insert  arg = String(arg); at the beginning of each score_function.  All the missions are working correctly, including using objective-number.  I'll make a pull request Monday for it and the XML/JS

**Pull request merged**
